<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PostsTest extends TestCase
{
    use WithFaker;
    /**
     *  Check index of posts for existent Posts (should be generated by seeder)
     *
     * @return void
     */
    public function testIndex()
    {
        $response = $this->get('/api/posts');
        $response->assertJson(["current_page"=>1]);
        $response->assertJsonCount(10,$key="data");
        $response->assertStatus(200);
    }

    /**
     *  Check if it can find a random post
     *
     * @return void
     */
    public function testFind() {
        $response = $this->get('/api/posts/show/3');
        $response->assertSuccessful();
        $response->assertJsonStructure([
            "title",
            "content",
            "views",
            "votes",
            "updated_at"
        ]);
    }

    public function testAdd() {
        $data = [
            "title"=>$this->faker->sentence,
            "content"=>$this->faker->text
        ];

        $response = $this->postJson('/api/posts/add',$data);
        $response->assertOk();
    }
}
